### ISSUE TITLE
Forge Liroth Server Support

### ISSUE THREAD

**Issue by Zelioth** [decodinatorX/Liroth-Revamped-Forge#1]
I am attempting to include this mod before pushing my next update which I wanted to do today. I have the mod pack working perfect but I am now testing my server files and for some reason it fails to load on the server entirely

MC 1.19.2
Forge : 43.1.34
Liroth  : 1.0.3
 
[crash-2022-10-09_15.37.1
[latest.log](https://github.com/decodinatorX/Liroth-Revamped-Forge/files/9742534/latest.log)
1-fml.txt](https://github.com/decodinatorX/Liroth-Revamped-Forge/files/9742532/crash-2022-10-09_15.37.11-fml.txt)
[crash-2022-10-09_15.35.52-fml.txt](https://github.com/decodinatorX/Liroth-Revamped-Forge/files/9742533/crash-2022-10-09_15.35.52-fml.txt)

**Comment by Zelioth** [comment]
Just to be sure it was Liroth I made a server with only it included and the same issue referenced. 
[crash-2022-10-09_16.22.38-fml.txt](https://github.com/decodinatorX/Liroth-Revamped-Forge/files/9742600/crash-2022-10-09_16.22.38-fml.txt)

**Comment by decodinatorX** [comment]
I have pushed a new update to Liroth: Revamped Forge, I implore you to try it now.

**Comment by decodinatorX** [comment]
The update has been approved, please update me on its playability as soon as possible! Please and Thank You.

**Comment by decodinatorX** [comment]
Closing this issue, as a response was not given within the week's amount of time of the original issue's opening.
