### ISSUE TITLE
Liroth Revamped (liroth) has failed to load correctly

### ISSUE THREAD

**Issue by netrunnernumber37** [decodinatorX/Liroth-Revamped-Forge#20]
Am getting this error attempting to start a Minecraft 1.20.1 server along with other mods, do you know what the cause could be? Crash report posted. 
[crash-2023-07-19_18.38.27-fml.txt](https://github.com/decodinatorX/Liroth-Revamped-Forge/files/12100883/crash-2023-07-19_18.38.27-fml.txt)

**Comment by netrunnernumber37** [comment]
I think the mod is actually just broken on servers currently.

**Comment by decodinatorX** [comment]
Oh shoot, will get to it right away! Thanks for alerting me!

**Comment by decodinatorX** [comment]
All things considered this may have something to do with the improper set up of the new title screen configuration, I need to go through a fit it up to be client-side only, as I may have forgotten to do such, working on that now.

**Comment by decodinatorX** [comment]
With the latest dev builds (1.19.2, 1.19.3, and 1.20/1.20.1) this issue has been resolved and will be in the next update being published now, thank you for your patience @netrunnernumber37.

**Comment by netrunnernumber37** [comment]
Thank you!
