### ISSUE TITLE
[1.19.2] Crash on world gen

### ISSUE THREAD

**Issue by Reshy** [decodinatorX/Liroth-Revamped-Forge#25]
Crash Log:  https://pastebin.com/HSCbcDuF

**Comment by decodinatorX** [comment]
This error is incredibly confusing to me unfortunately, I looked as thoroughly as I could to find a more defined culprit but all it tells me is that my mod, Liroth Boat specifically, is crashing with its rendering, the part that confuses me is that its occurring on WorldGen, which is odd as the boat itself is NEVER automatically placed during worldgen, doesn't generate in loot, or anything for that matter, it is a crafted item and only then when placed down does the entity spawn, in my dev build, I generate the world, place the boat down, swim around in it, and I receive no crash, so I am saying that this may just be mod incompatibility, another mod within that pack is causing issues with mine and until that is determined, there isn't much I can do from here!

I apologize for the wait and the inconvenience.

I will be closing the issue until further notice, you are free to comment as you wish.
