### ISSUE TITLE
Not launching on server

### ISSUE THREAD

**Issue by Dnalrah** [decodinatorX/Liroth-Revamped-Forge#29]
Liroth creates the error "net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Liroth (liroth) encountered an error during the load_registries event phase" when I try to load it in my server the logs file is here 
[latest.log](https://github.com/decodinatorX/Liroth-Revamped-Forge/files/14159366/latest.log)

**Comment by decodinatorX** [comment]
Hello, the report you sent me is for 1.16.5, where as it definitely states that Liroth was responsible for the crash, the version of Liroth for 1.16.5 and before are the Legacy versions of Liroth and are not to receive any future updates, as I have left that project behind, I apologize for the inconvenience.
