### ISSUE TITLE
Forever stuck on Joining World

### ISSUE THREAD

**Issue by Zarvera** [decodinatorX/Liroth-Revamped-Forge#3]
The latest Forge version.
I understand my world is probably messed up by a certain other mod (gets stuck forever on "saving world" on quitting) but at least i'm moving between Overworld and Nether with no problems. However, i'va made and activated Liroth portal and had several attempts to enter it and i just get stuck on Joining Worls forever. Had to NBT edit myself out of Liroth dimension to play at all
Another problem is that i can not find any informative log. latest.log has nothing whatsoever and there's no crash so no crash log either,
Any ideas on how to resolve this?

**Comment by decodinatorX** [comment]
With the lack of a log, there's not much I can really glean from, my literal only advice without a log is, don't play the mod, I apologize for the inconvenience.
