### ISSUE TITLE
Liroth furnace and splitter

### ISSUE THREAD

**Issue by duhswagttv** [decodinatorX/Liroth-Revamped-Forge#30]
On my private server through bisect hosting with my friends i cant open the slipper or liroth furnace is there any reason why theres no errors that occur but it opens in an SP

**Comment by decodinatorX** [comment]
[24](https://github.com/decodinatorX/Liroth-Revamped-Forge/issues/24)

**Comment by decodinatorX** [comment]
Latest build fixes this issue!
