### ISSUE TITLE
Crash crafting Liroth Shield

### ISSUE THREAD

**Issue by SHXRKIEgg** [decodinatorX/Liroth-Revamped-Forge#4]
Crash crafting Liroth Shield
Crash: https://pastebin.com/tQxxZaan

Also. I am the creator of Better MC & Medieval MC Modpacks and I am currently working on a new modpack to add your Dimension mod. I tried your book but still I have not manage to create the portal as I am stuck. I have made the shape and used the blocks but I dont kmow how to light it.

**Comment by decodinatorX** [comment]
Hi, can you please try the new update for me: 
https://www.curseforge.com/minecraft/mc-mods/liroth-revamped-forge/files/4360100

**Comment by SHXRKIEgg** [comment]
Still crashes https://pastebin.com/6CSfmEwD

Could you also help me and let me know how to get the portal working, because the guide doesnt seem to work.

**Comment by decodinatorX** [comment]
I believe the crashing is something to do with conflicting mods, though I can not say for sure as it worked fine on my side, with the portal, I realize the guide is outdated, should be updated now but in any case you need to create (at minimum) 8 dimensional communicators and arrange them in a flat square (this being without corners, similar to an end portal frame) and lighting it with a flint and steel, each portal works the same way!

**Comment by SHXRKIEgg** [comment]
Yeah this is conflicting but it only seems to be your mod having this issue with crafting. If you could maybe tell which mod is conflicting or fix the conflict that be great. Thanks for the guide, I willsee If I am able to do it

**Comment by SHXRKIEgg** [comment]
So I found the mod causing it, somehow its the https://www.curseforge.com/minecraft/mc-mods/good-ending mod
Could you fix it>?

**Comment by decodinatorX** [comment]
Thanks for pointing me in the right direction! I'll see to it asap!

**Comment by decodinatorX** [comment]
this bug is still being worked on, I apologize for the wait

**Comment by decodinatorX** [comment]
https://www.curseforge.com/minecraft/mc-mods/liroth-revamped-forge/files/4377780
This update fixes the issue
