### ISSUE TITLE
Crash on Viewing Liroth Advancements

### ISSUE THREAD

**Issue by TheQuantumTantrum** [decodinatorX/Liroth-Revamped-Forge#5]
The game crashes upon viewing Liroth advancements.

Crash Report: https://pastebin.com/FyMjbS96

MC: 1.19.2
Forge : 43.2.4
Liroth : 1.3.1 - No Title

**Comment by decodinatorX** [comment]
This was a bug rendering chests, this bug has been fixed in the latest patch.
