### ISSUE TITLE
Liroth Revamped has failed to load correctly

### ISSUE THREAD

**Issue by DarkDestrov** [decodinatorX/Liroth-Revamped-Forge#6]
I can't launch Minecraft 1.19.3, I got this message. I'm doing something wrong, or it's problem of a mod?
![image](https://user-images.githubusercontent.com/125287612/218496479-cffdf932-52ba-46e9-b044-001df065d3f5.png)

another link to the screenshot:
`https://sun9-west.userapi.com/sun9-40/s/v1/ig2/I3s-io5md5XO68NKvGwVnKk-sdenzgSRQcKng7JGYtsGJUrJBEnCPkOlWiJnHnceoA25xjjhS17EPXbQCjoQmHkQ.jpg?size=1229x1024&quality=96&type=album`

a crashlog:
[crash-2023-02-13_20.04.56-fml.txt](https://github.com/decodinatorX/Liroth-Revamped-Forge/files/10723492/crash-2023-02-13_20.04.56-fml.txt)

**Comment by Ka-Jin** [comment]
I'm getting the same error.
Edit: Tried it on my desktop as well as laptop and am getting the same issue.
Edit 2: Same on 1.19.2 with version 1.3.3 installed
Edit 3: I got 1.0.3 to work, trying to see exactly what update it breaks
Edit 4: 1.3.1 breaks
Edit 5: 1.1.3.3 Breaks
Edit 6: 1.0.3.1 and older work

**Comment by decodinatorX** [comment]
Hi! I apologize for dropping off the face of the earth, this error seems to be caused by a missing dependency, updates above 1.0.3 use Custom Portal API [Forge] located here:
https://www.curseforge.com/minecraft/mc-mods/custom-portal-api-forge

Again, I apologize for the wait!
