### ISSUE TITLE
Liroth boat model has failed to load.

### ISSUE THREAD

**Issue by PercyJames** [decodinatorX/Liroth-Revamped-Forge#7]
1.19.2 version. It seems to happen in any version of 1.19.2

[crash-2023-03-05_15.03.43-client.txt](https://github.com/decodinatorX/Liroth-Revamped-Forge/files/10892837/crash-2023-03-05_15.03.43-client.txt)

**Comment by PercyJames** [comment]
oh, and it's forge

**Comment by decodinatorX** [comment]
I apologize for the wait, a new update has been pushed to CurseForge, should have fixed the issue as this issue was prominent in 1.19.3 as well, and I fixed it there, so I have simply backported the fix, please test it within your modpack at your earliest discretion, have fun playing the mod!
